common:
    train_source_root: ./data/visda/train/
    train_target_root: ./data/visda/validation/
    train_source_source: ./data/visda/train/train.txt
    train_target_source: ./data/visda/validation/train.txt
    val_root: data/visda/validation/
    val_source: ./data/visda/validation/val.txt
    source_val_root: ./data/visda/train/
    source_val_source: ./data/visda/train/val.txt
    num_classes: 13
